apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 0.3.0
    helm:
      releaseName: eks
    chart: eck-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluentd
  syncPolicy:
    automated: {}
