apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: konga-ui
  template:
    metadata:
      labels:
        app: konga-ui
    spec:
      containers:
      - image: pantsel/konga:0.14.9
        name: konga-ui
        ports:
        - containerPort: 1337
        env:
        - name: DB_USER
          value: konga
        - name: DB_PASSWORD
          value: konga
        - name: DB_DATABASE
          value: konga
        - name: DB_HOST
          value: 10.107.138.133
        - name: DB_PORT
          value: "5432"
        - name: DB_ADAPTER
          value: postgres
  
