apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konga-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.5
    helm:
      releaseName: konga-postgresql
      parameters:
      - name: "global.postgresql.auth.database"
        value: konga
      - name: "global.postgresql.auth.username"
        value: konga
      - name: "global.postgresql.auth.password"
        value: konga
      - name: "image.debug"
        value: true
    chart: postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kong
  syncPolicy:
    automated: {}
