apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konga-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.8.1
    chart: postgresql
    helm:
      releaseName: konga-postgresql
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kong
  syncPolicy:
    automated: {}