apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.8.1
    helm:
      valueFiles:
        - values.yaml
      releaseName: sealed-secrets
    chart: sealed-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeseal
  syncPolicy:
    automated: {}


